# Generated by Django 2.1 on 2021-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DingTalkNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=100, unique=True, verbose_name='环境')),
                ('url', models.CharField(max_length=200, verbose_name='地址')),
            ],
            options={
                'verbose_name': '钉钉告警',
                'verbose_name_plural': '钉钉告警',
                'db_table': 'ding_talk_notify',
            },
        ),
    ]
